# -*- coding: utf-8 -*-
"""Nilai tertinggi siswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPzBdgFGX1a0JKUAFzUDylYIZcG3ToAF
"""

def input_nilai_siswa():

    nilai_siswa = []

    for i in range(5):
        while True:
            try:
                nilai = float(input(f"Input nilai siswa ke-{i+1}: "))
                if 0 <= nilai <= 100:
                    nilai_siswa.append(nilai)
                    break
                else:
                    print("Nilai harus dalam rentang 0-100. Silakan coba lagi.")
            except ValueError:
                print("Input tidak valid. Masukkan angka.")

    # Mencari nilai tertinggi dan indeksnya
    nilai_tertinggi = max(nilai_siswa)
    indeks_tertinggi = nilai_siswa.index(nilai_tertinggi)
    siswa_tertinggi = indeks_tertinggi + 1

    # Menampilkan hasil
    print("\nNilai semua siswa:", nilai_siswa)
    print(f"Nilai tertinggi: {nilai_tertinggi}")
    print(f"Diperoleh oleh siswa ke-{siswa_tertinggi}")

print("MENCARI NILAI TERTINGGI SISWA")
print("=============================")
input_nilai_siswa()
