# -*- coding: utf-8 -*-
"""Diskon ecommerce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JczvZByQXrNEuZlUqhwAZBXNfGta6yTG
"""

def hitung_total_bayar():

    try:
        total_belanja = float(input("Masukkan total belanja (Rp): "))

        if total_belanja > 500000:
            diskon = total_belanja * 0.1
            print(f"Selamat! Anda mendapatkan diskon 10%.")
        elif total_belanja < 500000:
            diskon = 0
            print(f"Maaf, Anda tidak mendapatkan diskon.")
        else:
            total_belanja = 500000
            diskon = 0
            total_bayar = total_belanja
            print(f"Belanja di atas Rp500.000 untuk mendapatkan diskon 10%.")

        total_bayar = total_belanja - diskon

        # Tampilkan rincian pembayaran
        print("\n===== RINCIAN PEMBAYARAN =====")
        print(f"Total Belanja: Rp{total_belanja:,.2f}".replace(",", "."))
        print(f"Diskon: Rp{diskon:,.2f}".replace(",", "."))
        print(f"Total Bayar: Rp{total_bayar:,.2f}".replace(",", "."))

        return {
            "total_belanja": total_belanja,
            "diskon": diskon,
            "total_bayar": total_bayar
        }

    except ValueError:
        print("Input tidak valid. Harap masukkan angka.")
        return None

if __name__ == "__main__":
    print("KALKULATOR DISKON E-COMMERCE")
    print("============================")
    hitung_total_bayar()
