# -*- coding: utf-8 -*-
"""Menghitung rata-rata dan cek kelulusan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9ae7GEKIzDBuw9mDQmSf9eHNBt4Pssj
"""

def hitung_kelulusan():

    try:
        nilai_matematika = float(input("Masukkan nilai Matematika: "))
        nilai_bahasa = float(input("Masukkan nilai Bahasa: "))
        nilai_ipa = float(input("Masukkan nilai IPA: "))

        for nilai in [nilai_matematika, nilai_bahasa, nilai_ipa]:
            if not (0 <= nilai <= 100):
                print("Error: Nilai harus dalam rentang 0-100.")
                return None

        jumlah_nilai = nilai_matematika + nilai_bahasa + nilai_ipa
        jumlah_mapel = 3
        rata_rata = jumlah_nilai / jumlah_mapel

        is_lulus = rata_rata >= 75
        status = "LULUS" if is_lulus else "TIDAK LULUS"

        # Menampilkan hasil
        print("\n===== HASIL PERHITUNGAN =====")
        print(f"Nilai Matematika: {nilai_matematika}")
        print(f"Nilai Bahasa: {nilai_bahasa}")
        print(f"Nilai IPA: {nilai_ipa}")
        print(f"Rata-rata nilai: {rata_rata:.2f}")
        print(f"Status kelulusan: {status}")

        if not is_lulus:
            poin_kurang = 75 - rata_rata
            print(f"Anda memerlukan {poin_kurang:.2f} poin lagi untuk lulus.")

        return {
            "nilai_matematika": nilai_matematika,
            "nilai_bahasa": nilai_bahasa,
            "nilai_ipa": nilai_ipa,
            "rata_rata": rata_rata,
            "status": status
        }

    except ValueError:
        print("Error: Input nilai harus berupa angka.")
        return None

if __name__ == "__main__":
    print("MENENTUKAN KELULUSAN BERDASARKAN RATA-RATA NILAI")
    print("================================================")
    hitung_kelulusan()

