# -*- coding: utf-8 -*-
"""Faktorial rekursif

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jmmwk5jfLKz1qhCJpHq8ymPAZJinMbye
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)

# Input dari pengguna
try:
    angka = int(input("Masukkan angka untuk dihitung faktorialnya: "))
    if angka < 0:
        print("Faktorial tidak terdefinisi untuk angka negatif.")
    else:
        hasil = faktorial(angka)
        print(f"Faktorial dari {angka} adalah {hasil}")
except ValueError:
    print("Masukkan angka bulat yang valid.")