# -*- coding: utf-8 -*-
"""Menghitung harga barang

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vDnyEbgaB5rHpxfaWCatzJGYJiBFKc0
"""

print("=== HITUNG TOTAL Pembelian ====")
print("Silakan masukkan harga 3 barang:")


harga_barang1 = float(input("Harga barang 1: Rp "))
harga_barang2 = float(input("Harga barang 2: Rp "))
harga_barang3 = float(input("Harga barang 3: Rp "))

# Menghitung total harga
total_harga = harga_barang1 + harga_barang2 + harga_barang3

# Menampilkan total harga
print("\n==== RINCIAN PEMBELIAN ====")
print(f"Harga barang 1: Rp {harga_barang1:,.2f}")
print(f"Harga barang 2: Rp {harga_barang2:,.2f}")
print(f"Harga barang 3: Rp {harga_barang3:,.2f}")
print("--------------------------")
print(f"Total harga  : Rp {total_harga:,.2f}")
print("==========================")
print("Terima kasih telah berbelanja!")