# -*- coding: utf-8 -*-
"""Menghitung harga barang

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vDnyEbgaB5rHpxfaWCatzJGYJiBFKc0
"""

def hitung_total(harga_barang1, harga_barang2, harga_barang3):
    return harga_barang1 + harga_barang2 + harga_barang3

if __name__ == "__main__":
    try:
        print("Masukkan harga 3 barang:")
        harga_barang1 = float(input("Harga barang ke-1: Rp "))
        harga_barang2 = float(input("Harga barang ke-2: Rp "))
        harga_barang3 = float(input("Harga barang ke-3: RP "))

        # Menghitung total harga
        total = hitung_total(harga_barang1, harga_barang2, harga_barang3)

        # Menampilkan total harga
        print("\n==== RINCIAN PEMBELIAN ====")
        print(f"Harga barang 1: Rp {harga_barang1:,.2f}")
        print(f"Harga barang 2: Rp {harga_barang2:,.2f}")
        print(f"Harga barang 3: Rp {harga_barang3:,.2f}")
        print("--------------------------")
        print(f"\nTotal Harga adalah: Rp{total:,.2f}")
        print("==========================")
        print("Terima kasih telah berbelanja!")


    except ValueError:
        print("Input harus berupa angka!")