# -*- coding: utf-8 -*-
"""Nilai tertinggi siswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPzBdgFGX1a0JKUAFzUDylYIZcG3ToAF
"""

# Inisialisasi list kosong
nilai_siswa = []

# Input nilai 5 siswa menggunakan loop
for i in range(5):
    while True:
        try:
            nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
            if 0 <= nilai <= 100:
                nilai_siswa.append(nilai)
                break
            else:
                print("Nilai harus antara 0 sampai 100.")
        except ValueError:
            print("Masukkan angka yang valid.")

# Mencari nilai tertinggi dan siswa keberapa yang mendapatkannya
nilai_tertinggi = max(nilai_siswa)
siswa_ke = nilai_siswa.index(nilai_tertinggi) + 1

# Menampilkan hasil
print("\n=== Hasil ===")
print(f"Nilai tertinggi adalah {nilai_tertinggi}")
print(f"Didapat oleh siswa ke-{siswa_ke}")